### ISSUE TITLE
Issue resolving depdencies

### ISSUE THREAD

**Issue by drtshock** [Maximvdw/MVdWPlaceholderAPI#1]
Issue with `LATEST` or `2.3.1-SHAPSHOT` versions of your placeholder API. If I go back to `2.2.3-SHAPSHOT` (version before you added the updater), then I don't have issues with not finding your updater binary.

I'm also not sure why you require me to have spigot 1.9 installed to build against your plugin.

> Could not resolve dependencies for project com.massivecraft:Factions:jar:1.6.9.5-U0.2.0-SNAPSHOT: The following artifacts could not be resolved: be.maximvdw:MVdWUpdater:jar:1.0.2-SNAPSHOT, org.spigotmc:spigot:jar:1.9: Could not find artifact be.maximvdw:MVdWUpdater:jar:1.0.2-SNAPSHOT in vault-repo (http://nexus.hc.to/content/repositories/pub_releases) -> [Help 1]

pom.xml
```       
       <repository>
            <id>mvdw-software</id>
            <url>http://repo.mvdw-software.be/content/groups/public/</url>
        </repository>

        <dependency>
            <groupId>be.maximvdw</groupId>
            <artifactId>MVdWPlaceholderAPI</artifactId>
            <version>2.3.1-SNAPSHOT</version>
        </dependency>

**Comment by drtshock** [comment]
Yeah, updating the spigot version in this project just makes it so the Updater project still has 1.9. You should be depending on `spigot-api` and not `spigot` as well since it doesn't seem like you hook any internals in these plugins outside of reflection.

**Comment by wyatt-herkamp** [comment]
I don't know either. I am trying to figure out what this plugin does that requires nms?

**Comment by Maximvdw** [comment]
Fixed in latest commit.
