### ISSUE TITLE
Build 87 Error in placeholders

### ISSUE THREAD

**Issue by x1p** [Maximvdw/MVdWPlaceholderAPI#15]
Thought I'd try out MVdWPlaceholderAPI v3.0.0 build 87
FeatherBoard v4.19.3 doesn't like it.

Part of all (endless) errors:
https://hastebin.com/qihipowara.cs

**Comment by Maximvdw** [comment]
v3.0 is not hooked to plugins yet as it is still being developed. Please use 2.5.1 until FeatherBoard and others have updated to 3.0
